version: "3.7"
services:
  mongo:
    image: mongo
    restart: always
    container_name: db-mongo
    ports:
      - 27017:27017
    networks:
      testing_net:
          ipv4_address: 172.28.1.1  
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
  mongo-express:
    image: mongo-express
    restart: always
    container_name: db-mongo-express
    links:
      - mongo
    ports:
      - 8081:8081
    networks:
      testing_net:
          ipv4_address: 172.28.1.3  
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root;
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234

#  app:
#    build:
#      context: .
#    ports:
#      - 5555:5555
#    container_name: SearchMoviesApplication
#    links:
#      - mongo
#    environment: 
#      WAIT_HOSTS: mongo:27017 
#    depends_on: 
#      - mongo
#    networks:
#      testing_net:
#          ipv4_address: 172.28.1.2
          
          
networks:
    testing_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16            
